version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mytesttask_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: myTestTaskService
      MONGO_INITDB_ROOT_PASSWORD: myTestTaskNonProdPassword
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mytesttask-api:
    image: ${DOCKER_REGISTRY-}mytesttaskapi
    build:
      context: .
      dockerfile: MyTestTask.API/Dockerfile
    container_name: mytesttask_api
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
      - "8081:8081"

volumes:
  mongodb_data:
